# Use generic build mode on Ubuntu
image: Ubuntu
build: off

environment:
  CODECOV_TOKEN: '0aa02c71-c79f-452e-bf87-63d51eea1241'

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - nvm use 16
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)
